services:  
  newsbot:  
    build: .  
    depends_on:  
      - mysql  
    restart: "on-failure"  
    environment:
      - NBT_ACCESS_TOKEN=${NBT_ACCESS_TOKEN}
      - USER_AGENT=${USER_AGENT}
      - UPDATE_PERIOD=${UPDATE_PERIOD}
      - LAST_UPDATED_FOLDER=${LAST_UPDATED_FOLDER}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - newsbot
 
  mysql:  
    image: mysql 
    volumes:  
        - newsbot-db:/var/lib/mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - newsbot
 
volumes:  
  newsbot-db: 

networks:
  newsbot: