services:  
  newsbot:  
    build: .  
    depends_on:  
      - mysql  
    restart: "on-failure"  
    env_file:
      - .env
    networks:
      - newsbot
 
  mysql:  
    image: mysql 
    volumes:  
        - newsbot-db:/var/lib/mysql  
    env_file:
      - .env
    networks:
      - newsbot
 
volumes:  
  newsbot-db: 

networks:
  newsbot: