trigger:
  branches:
    include:
      - main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: LintAndBuildDocker
  displayName: 'Lint and Build Docker'
  timeoutInMinutes: 10
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      pip install flake8
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 . --count --exit-zero --max-complexity=10 --statistics
    displayName: 'Lint with flake8'

- job: DockerBuild
  displayName: 'Docker Build and Publish Artifact'
  dependsOn: LintAndBuildDocker
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: |
      docker build -t newsbot:$(Build.SourceVersion) .
    displayName: 'Build Docker Image'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'dockerImage'
    displayName: 'Publish Docker Image as Artifact'
  